repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-symlinks
  - id: trailing-whitespace
    args: [--markdown-linebreak-ext=md]
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-toml
  - id: check-ast
  - id: check-added-large-files
  - id: check-merge-conflict
  - id: detect-private-key
  - id: debug-statements
  - id: check-json
  - id: pretty-format-json
    args: ['--autofix', '--indent=2']
- repo: https://github.com/psf/black
  rev: 22.10.0
  hooks:
  - id: black
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
  - id: isort
